# Generated by Django 2.2.28 on 2023-12-09 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 13, 27, 48, 315268), verbose_name='Опубликована'),
        ),
    ]
