# Generated by Django 2.2.28 on 2023-12-09 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20231209_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 14, 8, 3, 153476), verbose_name='Опубликована'),
        ),
    ]
