# Generated by Django 2.2.28 on 2023-12-09 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20231209_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 15, 9, 5, 837477), verbose_name='Опубликована'),
        ),
    ]
